"""Execute real edited implementations. Syntax failures do not count as kills."""
import ast
import hashlib
import os
from pathlib import Path
import shutil
import subprocess
import sys
import tempfile

ROOT = Path(__file__).parents[2]
ENGINE = ROOT / "examples/autogenerated/safe-filing"
TEST = Path(__file__).with_name("test_filing.py")


def replace_once(text, old, new):
    if old not in text:
        raise RuntimeError("mutant edit no longer applies: " + old)
    return text.replace(old, new, 1)


def main():
    variants = [
        ("body-select", "test_corpus_boundaries_bytes_and_selection", {
            "framing.py": [("if not line:\n            break", "if not line:\n            continue"),
                           ("in_header = False\n                header_line.clear()", "in_header = True\n                header_line.clear()")]}),
        ("omit-sender", "test_policy_independent_of_parser", {
            "spec_list.py": [('b"from", b"sender",', 'b"from",')]}),
        ("wrong-message", "test_move_and_rerun_preserve_occurrences", {
            "filing.py": [("bool(int(row[5])) == selected:", "bool(int(row[5])) != selected:")]}),
        ("drop-envelope", "test_corpus_boundaries_bytes_and_selection", {
            "filing.py": [("copy_range(source, sink, int(row[2]), int(row[3]))", "copy_range(source, sink, int(row[2]) + len(decoded(row[6])), int(row[3]))")]}),
        ("merge-records", "test_move_and_rerun_preserve_occurrences", {
            "framing.py": [("written = sink.write(data)", 'data = data.replace(b"\\nFrom ", b"\\nNotFrom ")\n        written = sink.write(data)')]}),
        ("split-record", "test_corpus_boundaries_bytes_and_selection", {
            "framing.py": [("written = sink.write(data)", 'data = data.replace(b">From ", b"From ")\n        written = sink.write(data)')]}),
        ("delete-before-verify", "test_archive_verification_precedes_source_mutation", {
            "filing.py": [("hook(\"after-archive-write\")", 'source.write_bytes(b"")\n            hook("after-archive-write")')]}),
        ("stale-rewrite", "test_stale_source_cases", {
            "filing.py": [("def verify_plan(path, meta, directory):", "def verify_plan(path, meta, directory):\n    return"),
                          ('source = Path(os.fsdecode(decoded(meta["source"][0])))', 'source = Path(os.fsdecode(decoded(meta["source"][0])))'),
                          ('check_paths(source, destination)\n    plan_digest', 'check_paths(source, destination)\n    meta["source"][1] = fingerprint(source)\n    plan_digest')]}),
        ("drop-keeper", "test_move_and_rerun_preserve_occurrences", {
            "filing.py": [("def copy_records(plan, source, sink, selected):", "def copy_records(plan, source, sink, selected):\n    if not selected:\n        return")]}),
        ("duplicate-selected", "test_move_and_rerun_preserve_occurrences", {
            "filing.py": [("copy_range(source, sink, int(row[2]), int(row[3]))", "copy_range(source, sink, int(row[2]), int(row[3]))\n            if selected:\n                copy_range(source, sink, int(row[2]), int(row[3]))")]}),
        ("interchange-live-spool", "test_path_refusals", {
            "filing.py": [("if live_spool is not None and source != absolute(live_spool):", "if False:")]}),
        ("accept-alias", "test_path_refusals", {
            "filing.py": [("if source == destination or (destination.exists() and os.path.samefile(source, destination)):", "if False:")]}),
        ("partial-write-success", "test_short_write_and_raises_after_n_bytes", {
            "framing.py": [('raise Refusal("short destination write")', 'return')]}),
    ]
    failures = 0
    for name, test, edits in variants:
        with tempfile.TemporaryDirectory() as location:
            target = Path(location)
            for path in ENGINE.glob("*.py"):
                shutil.copyfile(path, target / path.name)
            digest = hashlib.sha256()
            for name_file, changes in edits.items():
                path = target / name_file
                code = path.read_text()
                for old, new in changes:
                    code = replace_once(code, old, new)
                ast.parse(code)  # construction/parse errors do not count as kills
                path.write_text(code)
                digest.update(code.encode())
            result = subprocess.run([sys.executable, str(TEST), "FilingTests." + test],
                       env=dict(os.environ, MBOX_ENGINE=str(target), MBOX_QUICK="1"),
                       stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
            killed = result.returncode != 0 and "Ran 1 test" in result.stdout and "FAILED (" in result.stdout
            print("\t".join((name, "KILLED" if killed else "SURVIVED", test, digest.hexdigest())))
            if not killed:
                print(result.stdout)
                failures += 1
    print("mutation-summary\t%d\t%d" % (len(variants) - failures, failures))
    return bool(failures)


if __name__ == "__main__":
    sys.exit(main())
