import ast
import errno
import hashlib
import io
import os
from pathlib import Path
import subprocess
import sys
import tempfile
import time
import tracemalloc
import unittest
from unittest.mock import patch

ENGINE = Path(os.environ.get("MBOX_ENGINE", Path(__file__).parents[2] / "examples/autogenerated/safe-filing"))
sys.path.insert(0, str(ENGINE))
import filing
import framing
import spec_list
from corpus import cases, entry, expected_ranges


class FilingTests(unittest.TestCase):
    def setUp(self):
        self.temporary = tempfile.TemporaryDirectory()
        self.root = Path(self.temporary.name)
        (self.root / "DISPOSABLE-MAILBOX-TEST-ONLY").touch()
        self.source = self.root / "incoming"
        self.archive = self.root / "archive"
        self.plan = self.root / "plan.tsv"
        self.entries = [entry(b"Subject: SPEC-LIST\nMessage-ID: <same>\n", selected=True), entry(),
                        entry(b"Subject: SPEC-LIST\nMessage-ID: <same>\n", selected=True)]
        self.original = b"".join(x.raw for x in self.entries)
        self.selected = b"".join(x.raw for x in self.entries if x.selected)
        self.kept = b"".join(x.raw for x in self.entries if not x.selected)
        self.source.write_bytes(self.original)

    def tearDown(self):
        self.temporary.cleanup()

    def make_plan(self, mode="move"):
        with self.plan.open("w", encoding="ascii") as stream:
            filing.write_plan(self.source, self.archive, mode, stream)

    def test_policy_independent_of_parser(self):
        for name, entries in cases().items():
            for item in entries:
                with self.subTest(case=name):
                    self.assertEqual(bool(spec_list.evidence(framing.fields(item.header))), item.selected)
        for header in spec_list.SEARCH_HEADERS:
            self.assertTrue(spec_list.evidence([(header, b"SPEC-LIST")]))
            self.assertFalse(spec_list.evidence([(header, b"SPEC LIST")]))
        self.assertFalse(spec_list.evidence([(b"List-ID", b"SPEC-LIST")]))

    def test_corpus_boundaries_bytes_and_selection(self):
        for name, entries in cases().items():
            with self.subTest(case=name):
                raw = b"".join(x.raw for x in entries)
                items = list(framing.records(io.BytesIO(raw)))
                self.assertEqual([(x.start, x.end) for x in items], list(expected_ranges(entries)))
                self.assertEqual([x.envelope for x in items], [x.envelope for x in entries])
                self.assertEqual([x.header for x in items], [x.header for x in entries])
                self.assertEqual([bool(spec_list.evidence(framing.fields(x.header))) for x in items],
                                 [x.selected for x in entries])
                self.assertEqual([x.digest for x in items], [hashlib.sha256(x.raw).hexdigest() for x in entries])
                self.source.write_bytes(raw)
                self.archive.unlink(missing_ok=True)
                self.make_plan("copy")
                # Each corpus copy runs the actual executor, not a stdlib mailbox API.
                filing.execute(self.plan, self.root)
                self.assertEqual(self.archive.read_bytes(), b"".join(x.raw for x in entries if x.selected))
                self.assertEqual(self.source.read_bytes(), raw)
                self.assertEqual(filing.execute(self.plan, self.root), "already-complete")
                import shutil
                shutil.rmtree(str(self.plan) + ".transaction")

    def test_shared_original_fixture_ranges(self):
        import json
        fixtures = Path(__file__).parents[2] / "fixtures"
        manifest = json.loads((fixtures / "manifest.json").read_text())
        for name, contract in manifest["fixtures"].items():
            with self.subTest(case=name), (fixtures / name).open("rb") as stream:
                self.assertEqual(filing.digest_file(fixtures / name), contract["sha256"])
                found = list(framing.records(stream))
                self.assertEqual(len(found), contract["message_count"])
                if "ranges" in contract:
                    self.assertEqual([(x.start, x.end) for x in found],
                                     [tuple(x["whole_entry_range"]) for x in contract["ranges"]])
                if "selected_message_ids" in contract:
                    selected = []
                    for item in found:
                        values = list(framing.fields(item.header))
                        if spec_list.evidence(values):
                            selected.extend(value.decode() for key, value in values if key.lower() == b"message-id")
                    self.assertEqual(selected, contract["selected_message_ids"])

    def test_dry_run_stable_and_non_mutating(self):
        before = filing.fingerprint(self.source)
        first, second = io.StringIO(), io.StringIO()
        for output in (first, second):
            filing.write_plan(self.source, self.archive, "move", output)
        self.assertEqual(first.getvalue(), second.getvalue())
        self.assertEqual(filing.fingerprint(self.source), before)
        self.assertFalse(self.archive.exists())
        self.assertIn("mailbox-mutation\tnone", first.getvalue())
        self.assertIn("summary\t3\t2\t" + str(len(self.selected)) + "\t1\t" + str(len(self.kept)), first.getvalue())
        self.assertIn(filing.encoded(self.source), first.getvalue())
        self.assertIn(filing.encoded(self.archive), first.getvalue())
        self.assertIn(str(self.source), first.getvalue())
        self.assertIn(str(self.archive), first.getvalue())
        self.assertIn("<same>", first.getvalue())
        self.assertIn("SPEC-LIST", first.getvalue())
        self.assertEqual(first.getvalue().count("record\t"), 3)
        self.assertIn(hashlib.sha256(self.entries[0].raw).hexdigest(), first.getvalue())

    def test_move_and_rerun_preserve_occurrences(self):
        self.archive.write_bytes(self.entries[0].raw)  # equal bytes predate transaction
        self.make_plan()
        self.assertEqual(filing.execute(self.plan, self.root), "complete")
        self.assertEqual(self.source.read_bytes(), self.kept)
        self.assertEqual(self.archive.read_bytes(), self.entries[0].raw + self.selected)
        backup = Path(str(self.plan) + ".transaction/source.original")
        self.assertEqual(backup.read_bytes(), self.original)
        self.assertEqual(filing.execute(self.plan, self.root), "already-complete")
        self.assertEqual(self.archive.read_bytes(), self.entries[0].raw + self.selected)

    def test_failures_and_recovery(self):
        stages = ["before-archive", "archive-open", "archive-write", "archive-fsync", "archive-close",
                  "after-archive-write", "archive-verify", "archive-replace", "after-archive-commit",
                  "after-archive-verification", "source-backup-open", "source-backup-write",
                  "source-backup-fsync", "source-backup-close", "source-open", "source-write",
                  "source-fsync", "source-close", "source-verify", "before-source-commit",
                  "source-replace", "after-source-commit", "receipt-write", "state-fsync", "state-close"]
        for stage in stages:
            with self.subTest(stage=stage):
                self.source.write_bytes(self.original)
                self.archive.unlink(missing_ok=True)
                self.make_plan()
                def fail(at):
                    if at == stage:
                        raise OSError(errno.ENOSPC, "No space left on device (ENOSPC): " + stage)
                with self.assertRaises(OSError):
                    filing.execute(self.plan, self.root, fail)
                if stage not in ("after-source-commit", "receipt-write"):
                    self.assertEqual(self.source.read_bytes(), self.original)
                else:
                    self.assertEqual(self.source.read_bytes(), self.kept)
                    self.assertEqual(self.archive.read_bytes(), self.selected)
                    self.assertEqual(Path(str(self.plan) + ".transaction/source.original").read_bytes(), self.original)
                filing.execute(self.plan, self.root)
                self.assertEqual(self.source.read_bytes(), self.kept)
                self.assertEqual(self.archive.read_bytes(), self.selected)
                import shutil
                shutil.rmtree(str(self.plan) + ".transaction")

    def test_real_process_interruption_and_restart(self):
        # Multiple bounded writes make the write interruptions genuinely partial,
        # rather than terminating before the first byte or after a whole record.
        self.entries = [entry(b"Subject: SPEC-LIST\n", b"x" * (2 * framing.CHUNK) + b"\n", True),
                        entry(body=b"y" * (2 * framing.CHUNK) + b"\n"),
                        entry(b"Subject: SPEC-LIST\n", selected=True)]
        self.original = b"".join(x.raw for x in self.entries)
        self.selected = b"".join(x.raw for x in self.entries if x.selected)
        self.kept = b"".join(x.raw for x in self.entries if not x.selected)
        stages = ["before-archive", "archive-write", "after-archive-write", "archive-verify",
                  "after-archive-commit", "after-archive-verification", "source-write",
                  "before-source-commit", "after-source-commit", "receipt-write"]
        for stage in stages:
            with self.subTest(stage=stage):
                self.source.write_bytes(self.original)
                self.archive.unlink(missing_ok=True)
                self.make_plan()
                code = """import filing, os
hits = 0
def interrupt(stage):
    global hits
    if stage == os.environ['STAGE']:
        hits += 1
        if hits == (2 if stage in ('archive-write', 'source-write') else 1):
            os._exit(73)
filing.execute(os.environ['PLAN'], os.environ['ROOT'], interrupt)
"""
                result = subprocess.run([sys.executable, "-c", code], env=dict(os.environ, PYTHONPATH=str(ENGINE),
                                         PLAN=str(self.plan), ROOT=str(self.root), STAGE=stage))
                self.assertEqual(result.returncode, 73)
                if stage in ("archive-write", "source-write"):
                    partial = Path(str(self.plan) + ".transaction/" +
                                   ("archive.prepared" if stage == "archive-write" else "source.prepared"))
                    self.assertGreater(partial.stat().st_size, 0)
                    self.assertLess(partial.stat().st_size, len(self.selected if stage == "archive-write" else self.kept))
                if stage not in ("after-source-commit", "receipt-write"):
                    self.assertEqual(self.source.read_bytes(), self.original)
                filing.execute(self.plan, self.root)
                self.assertEqual(self.source.read_bytes(), self.kept)
                self.assertEqual(self.archive.read_bytes(), self.selected)
                import shutil
                shutil.rmtree(str(self.plan) + ".transaction")

    def test_short_write_and_raises_after_n_bytes(self):
        for failure in ("short", "raise"):
            sink = io.BytesIO()
            class BrokenSink:
                def write(inner, data):
                    sink.write(data[:17])
                    if failure == "raise":
                        raise OSError("write raised after 17 bytes")
                    return 17
            with self.assertRaises((framing.Refusal, OSError)):
                framing.copy_range(io.BytesIO(self.original), BrokenSink(), 0, len(self.original))
            self.assertEqual(sink.getvalue(), self.original[:17])
        self.make_plan()
        real_prepare = filing.prepare_file
        def broken_prepare(path, producer, hook, stage):
            if stage == "archive":
                path.write_bytes(self.selected[:17])
                raise OSError("partial archive write")
            return real_prepare(path, producer, hook, stage)
        with patch.object(filing, "prepare_file", broken_prepare), self.assertRaises(OSError):
            filing.execute(self.plan, self.root)
        self.assertEqual(self.source.read_bytes(), self.original)
        self.assertFalse(self.archive.exists())
        filing.execute(self.plan, self.root)
        self.assertEqual(self.archive.read_bytes(), self.selected)

    def test_archive_verification_precedes_source_mutation(self):
        self.make_plan()
        def corrupt(stage):
            if stage == "archive-verify":
                Path(str(self.plan) + ".transaction/archive.prepared").write_bytes(b"broken")
        with self.assertRaises(framing.Refusal):
            filing.execute(self.plan, self.root, corrupt)
        self.assertEqual(self.source.read_bytes(), self.original)
        self.assertFalse(self.archive.exists())

    def test_baseline_backup_corruption_and_failures(self):
        baseline = entry(b"Subject: old archive\n").raw
        self.archive.write_bytes(baseline)
        self.make_plan()
        def corrupt(stage):
            if stage == "archive-backup-close":
                # Flush has already happened, so this modifies the persisted copy.
                path = Path(str(self.plan) + ".transaction/archive.original")
                with path.open("r+b") as stream:
                    stream.seek(len(b"From "))
                    stream.write(b"Y")
        with self.assertRaises(framing.Refusal):
            filing.execute(self.plan, self.root, corrupt)
        self.assertEqual(self.source.read_bytes(), self.original)
        self.assertEqual(self.archive.read_bytes(), baseline)
        filing.execute(self.plan, self.root)
        self.assertEqual(self.archive.read_bytes(), baseline + self.selected)

    def test_actual_fsync_failures_recover(self):
        import shutil
        real_sync = os.fsync
        baseline = entry(b"Subject: older archive\n").raw
        for fail_at in range(1, 24):
            with self.subTest(fsync_call=fail_at):
                self.source.write_bytes(self.original)
                self.archive.write_bytes(baseline)
                self.make_plan()
                calls = 0
                injected = False
                def fail(descriptor):
                    nonlocal calls, injected
                    calls += 1
                    if calls == fail_at:
                        injected = True
                        raise OSError(errno.EIO, "Input/output error (EIO): sync injection")
                    real_sync(descriptor)
                try:
                    with patch.object(os, "fsync", fail):
                        filing.execute(self.plan, self.root)
                except OSError:
                    if self.source.read_bytes() != self.original:
                        self.assertEqual(self.source.read_bytes(), self.kept)
                        self.assertEqual(self.archive.read_bytes(), baseline + self.selected)
                        self.assertEqual(Path(str(self.plan) + ".transaction/source.original").read_bytes(), self.original)
                self.assertTrue(injected, "declared fsync failure point was never reached")
                filing.execute(self.plan, self.root)
                self.assertEqual(self.source.read_bytes(), self.kept)
                self.assertEqual(self.archive.read_bytes(), baseline + self.selected)
                shutil.rmtree(str(self.plan) + ".transaction")

    def test_source_inside_temporary_output_refused(self):
        directory = Path(str(self.plan) + ".transaction")
        directory.mkdir()
        self.source = directory / "source.prepared"
        self.source.write_bytes(self.original)
        self.make_plan()
        with self.assertRaises(framing.Refusal):
            filing.execute(self.plan, self.root)
        self.assertEqual(self.source.read_bytes(), self.original)
        self.assertFalse(self.archive.exists())

    def test_orphaned_outputs_without_journal_refused(self):
        self.make_plan()
        directory = Path(str(self.plan) + ".transaction")
        directory.mkdir()
        partial = directory / "archive.prepared"
        partial.write_bytes(self.selected[:17])
        with self.assertRaises(framing.Refusal):
            filing.execute(self.plan, self.root)
        self.assertEqual(partial.read_bytes(), self.selected[:17])
        self.assertEqual(self.source.read_bytes(), self.original)
        self.assertFalse(self.archive.exists())

    def test_stale_source_cases(self):
        def append():
            with self.source.open("ab") as stream:
                stream.write(entry().raw)
        mutations = {
            "append": append,
            "replace-inode": lambda: self.replace_source(self.original),
            "shrink": lambda: self.source.write_bytes(self.original[:30]),
            "prefix": lambda: self.source.write_bytes(b"X" + self.original[1:]),
            "metadata": lambda: os.chmod(self.source, 0o640),
        }
        for name, change in mutations.items():
            with self.subTest(change=name):
                self.source.write_bytes(self.original)
                os.chmod(self.source, 0o600)
                self.make_plan()
                change()
                before = self.source.read_bytes()
                with self.assertRaises(framing.Refusal):
                    filing.execute(self.plan, self.root)
                self.assertEqual(self.source.read_bytes(), before)
                self.assertFalse(self.archive.exists())

    def replace_source(self, raw):
        temporary = self.root / "delivery-replacement"
        temporary.write_bytes(raw)
        os.replace(temporary, self.source)

    def test_delivery_at_commit_boundary_refused(self):
        self.make_plan()
        def append(stage):
            if stage == "before-source-commit":
                with self.source.open("ab") as stream:
                    stream.write(entry().raw)
        with self.assertRaises(framing.Refusal):
            filing.execute(self.plan, self.root, append)
        self.assertEqual(self.source.read_bytes(), self.original + entry().raw)
        self.assertEqual(self.archive.read_bytes(), self.selected)

    def test_path_refusals(self):
        for source, destination in ((self.source, self.source), (self.root / "missing", self.archive),
                                    (self.source, self.root / "unavailable" / "archive"),
                                    (Path("incoming"), self.archive)):
            with self.assertRaises(framing.Refusal):
                filing.write_plan(source, destination, "move", io.StringIO())
        alias = self.root / "alias"
        alias.symlink_to(self.source)
        with self.assertRaises(framing.Refusal):
            filing.write_plan(self.source, alias, "move", io.StringIO())
        alias.unlink()
        os.link(self.source, alias)
        with self.assertRaises(framing.Refusal):
            filing.write_plan(self.source, alias, "move", io.StringIO())
        alias.unlink()
        with self.assertRaises(framing.Refusal):
            filing.write_plan(self.source, self.archive, "move", io.StringIO(), "/var/mail/isomorphisms")
        self.assertEqual(self.source.read_bytes(), self.original)

    def test_unmarked_root_and_temporary_collision(self):
        self.make_plan()
        (self.root / "DISPOSABLE-MAILBOX-TEST-ONLY").unlink()
        with self.assertRaises(framing.Refusal):
            filing.execute(self.plan, self.root)
        self.assertFalse(self.archive.exists())
        (self.root / "DISPOSABLE-MAILBOX-TEST-ONLY").touch()
        directory = Path(str(self.plan) + ".transaction")
        directory.mkdir()
        (directory / "archive.prepared").symlink_to(self.source)
        with self.assertRaises(framing.Refusal):
            filing.execute(self.plan, self.root)
        self.assertEqual(self.source.read_bytes(), self.original)

    def test_changed_plan_and_executor_and_partial_destination(self):
        self.make_plan()
        before = self.plan.read_text()
        self.plan.write_text(before.replace("mode\tmove", "mode\tcopy"))
        with self.assertRaises(framing.Refusal):
            filing.execute(self.plan, self.root)
        self.plan.write_text(before)
        with patch.object(filing, "executor_digest", return_value="changed"), self.assertRaises(framing.Refusal):
            filing.execute(self.plan, self.root)
        self.archive.write_bytes(b"partial")
        with self.assertRaises(framing.Refusal):
            filing.execute(self.plan, self.root)
        self.assertEqual(self.source.read_bytes(), self.original)

    def test_no_final_newline_archive_refused(self):
        self.archive.write_bytes(entry(body=b"tail").raw)
        self.make_plan()
        with self.assertRaises(framing.Refusal):
            filing.execute(self.plan, self.root)
        self.assertEqual(self.source.read_bytes(), self.original)
        self.assertEqual(self.archive.read_bytes(), entry(body=b"tail").raw)

    def test_permissions_open_and_replace_failures(self):
        self.make_plan()
        original_open = open
        def denied(path, mode="r", *args, **kwargs):
            if str(path).endswith("archive.prepared") and "x" in mode:
                raise PermissionError(errno.EACCES, "Permission denied (EACCES)")
            return original_open(path, mode, *args, **kwargs)
        with patch("builtins.open", denied), self.assertRaises(PermissionError):
            filing.execute(self.plan, self.root)
        self.assertEqual(self.source.read_bytes(), self.original)
        self.assertFalse(self.archive.exists())
        original_replace = os.replace
        def denied_replace(old, new):
            if new == self.source:
                raise PermissionError("source rename denied")
            return original_replace(old, new)
        with patch.object(os, "replace", denied_replace), self.assertRaises(PermissionError):
            filing.execute(self.plan, self.root)
        self.assertEqual(self.source.read_bytes(), self.original)
        self.assertEqual(self.archive.read_bytes(), self.selected)
        filing.execute(self.plan, self.root)
        self.assertEqual(self.source.read_bytes(), self.kept)

    def test_bounded_large_single_line_and_many_messages(self):
        if os.environ.get("MBOX_QUICK"):
            self.skipTest("large resource suite excluded only in mutation subprocesses")
        started = time.monotonic()
        with self.source.open("wb") as stream:
            stream.write(b"From x\nSubject: SPEC-LIST\n\n")
            for _ in range(2048):  # 128 MiB, one body line, no final newline
                stream.write(b"x" * 65536)
        class BoundedReader:
            def __init__(inner, stream): inner.stream = stream
            def readline(inner, size=-1):
                self.assertGreater(size, 0)
                self.assertLessEqual(size, framing.CHUNK)
                return inner.stream.readline(size)
        tracemalloc.start()
        with self.source.open("rb") as stream:
            count = sum(1 for _ in framing.records(BoundedReader(stream)))
        self.make_plan("copy")
        filing.execute(self.plan, self.root)
        peak_one = tracemalloc.get_traced_memory()[1]
        tracemalloc.stop()
        self.assertEqual(count, 1)
        self.assertLess(peak_one, 16 * 1024 * 1024)
        self.assertEqual(filing.digest_file(self.archive), filing.digest_file(self.source))
        import shutil
        shutil.rmtree(str(self.plan) + ".transaction")
        self.archive.unlink()
        with self.source.open("wb") as stream:
            for _ in range(100000):
                stream.write(b"From x\nSubject: SPEC-LIST\n\nbody\n")
        tracemalloc.start()
        self.make_plan("copy")
        peak_many = tracemalloc.get_traced_memory()[1]
        tracemalloc.stop()
        self.assertLess(peak_many, 16 * 1024 * 1024)
        summary = filing.plan_metadata(self.plan)["summary"]
        self.assertEqual(summary[:2], ["100000", "100000"])
        print("RESOURCE single_body=128MiB messages=100000 peak_one=%d peak_many=%d seconds=%.2f" %
              (peak_one, peak_many, time.monotonic() - started))

    def test_header_limits_and_preamble_refuse(self):
        for raw in (b"preamble\n" + self.original,
                    b"From x\nSubject: " + b"x" * (framing.HEADER_LIMIT + 1),
                    b"From " + b"x" * framing.ENVELOPE_LIMIT):
            with self.assertRaises(framing.Refusal):
                list(framing.records(io.BytesIO(raw)))

    def test_python39_syntax(self):
        for name in ("framing.py", "spec_list.py", "filing.py"):
            ast.parse((ENGINE / name).read_text(), feature_version=(3, 9))


if __name__ == "__main__":
    unittest.main(verbosity=2)
